build:
  cuda_version: 12.1.1
  python_packages:
  - "torch==2.3.1"
  - "accelerate==0.31.0"
  - "transformers==4.43.0" 
  - "bitsandbytes"
  - "hf-transfer==0.1.9"
  - "huggingface-hub==0.27.1"
  run:
  - "pip install packaging"
  - "pip install flash_attn==2.5.8"
